version: '3.8'

services:
  order-service-postgres:
    image: postgres:15
    container_name: order-service-postgres
    environment:
      POSTGRES_DATABASE: order_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devsecops
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql



  zookeeper:
      image: confluentinc/cp-zookeeper:7.5.0
      hostname: zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  broker:
      container_name: broker
      image: confluentinc/cp-kafka:7.5.0
      ports:
        - "9092:9092"
        - "29092:29092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  schema-registry:
      image: confluentinc/cp-schema-registry:7.5.0
      hostname: schema-registry
      container_name: schema-registry
      depends_on:
        - broker
      ports:
        - "8085:8081"
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:29092
        SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081

  kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      ports:
        - "8086:8080"
      depends_on:
        - broker
      environment:
        KAFKA_CLUSTERS_NAME: local
        KAFKA_CLUSTERS_BOOTSTRAPSERVERS: broker:29092
        KAFKA_CLUSTERS_SCHEMAREGISTRY: http://schema-registry:8081
        DYNAMIC_CONFIG_ENABLED: 'true'

